# Generated by Django 3.1.1 on 2020-09-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
