# Generated by Django 3.1.3 on 2020-11-20 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_leader_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_item', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField(default='About my sales', max_length=500)),
                ('image', models.FileField(upload_to='marketplace/')),
                ('contact', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Community_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='event_images')),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.community')),
            ],
        ),
    ]
