# Generated by Django 3.1.3 on 2020-11-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Md', 'Madam'), ('Dr', 'Dr')], max_length=100),
        ),
        migrations.AlterField(
            model_name='leader',
            name='category',
            field=models.CharField(blank=True, choices=[('Patron', 'Patron'), ('Chairperson', 'Chairperson'), ('Vice-Chairperson', 'Vice-Charperson'), ('Secretary', 'Secretary'), ('Organizing Sec', 'Organizing Sec'), ('Treasurer', 'Treasurer'), ('Auditor', 'Auditor'), ('AI $ IoT team Lead', 'AI $ IoT team Lead'), ('Cyber Security Lead', 'Cyber Security Lead'), ('Opensource Lead', 'Opensource Lead'), ('Future comm lead', 'Future comm lead'), ('WebDevOps Lead', 'WebDevOps Lead')], max_length=100),
        ),
    ]
