# Generated by Django 3.1.3 on 2020-11-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201120_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(default='community_images/default.jpg', upload_to='comunity_images/'),
        ),
    ]
