# Generated by Django 3.1.3 on 2020-11-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_leader_category'),
        ('mainapp', '0007_auto_20201120_2206'),
    ]

    operations = [
    ]
